---
swagger: "2.0"
info:
  description: "Описание API системы проведения стажировок в Лиге цифровой экономики."
  version: "1.0.6"
  title: "Swagger LIGA Course"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "liga.swagger.io"
basePath: "/v2"
tags:
- name: "Course"
  description: "Operations about course"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "User"
  description: "Operations about user"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "Promo"
  description: "Operations about course preparations"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /course:
    post:
      tags:
      - "Course"
      summary: "Создание стажировки"
      description: ""
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Поля таблицы Course"
        required: true
        schema:
          $ref: "#/definitions/Course"
      responses:
        201:
          description: "successful operation"
          schema:
             type: "object"
             properties:
               id:
                type: "integer"
                format: "int64"
  /course/{courseId}:
    patch:
      tags:
      - "Course"
      summary: "Редактирование стажировки"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "courseId"
        required: true
        in: "path"
        description: "ID стажировки, которую нужно поменять"
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Поля для изменения"
        schema:
          $ref: "#/definitions/Course"
      responses:
        200:
          description: "Ok"
  /course/archived:  
    get:
      tags:
      - "Course"
      summary: "Получение всех стажировок с фильтрацией по статусу Архив"
      description: ""
      operationId: "archived"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "archived"
        in: "query"
        required: false
        description: "Помещена стажировка в архив или нет"
        type: "string"
      responses:
        200:
          description: "Успешная операция"
          schema:
            $ref: "#/definitions/Courses"  
  /user/courses/{courseId}/roles:
    post:
      tags:
      - "User"
      summary: "Назначение пользователю роли"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "courseId"
        required: true
        in: "path"
        description: "ID стажировки"
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Поля запроса"
        schema:
          $ref: "#/definitions/AssignedRole" 
      responses:
        201:
          description: "Успешная операция"
  /user/courses/{courseId}/security-check/{profileId}:
    post:
      tags:
      - "User"
      summary: "Отправка кандидата на согласование в СБ"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "courseId"
        required: true
        in: "path"
        description: "ID стажировки"
        type: "integer"
        format: "int64"
      - name: "profileId"
        required: true
        in: "path"
        description: "ID кандидата, которого нужно согласовать"
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Ok"
  /user/registration:
    post:
      tags:
      - "User"
      summary: "Регистрация пользователя в системе"
      description: ""
      operationId: "loginUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Поле запроса"
        required: true
        schema:
          $ref: "#/definitions/Username"
      responses:
        201:
          description: "Успешная регистрация"
        400:
          description: "Ответ в случае ошибки"
  /user/auth:
    post:
      tags:
      - "User"
      summary: "Аутентификация пользователя в системе"
      description: ""
      operationId: "AuthUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/Credentials"
      responses:
        201:
          description: "Успешная операция"
        400:
          description: "Ответ в случае ошибки"
  /user/course/{courseId}/students:
    get:
      tags:
      - "User"
      summary: "Получить список всех стажеров"
      description: ""
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "courseId"
        required: true
        in: "path"
        description: "ID стажировки"
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Успешная операция"
          schema:
            $ref: "#/definitions/StudentList"   
  /user/hr-promo:
    post:
      tags:
      - "User"
      summary: "Рекомендация стажера к трудоустройству"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Поля запроса"
        schema:
          $ref: "#/definitions/StudentforHR" 
      responses:
        201:
          description: "Успешная операция"   
  /user/course/{courseId}/students/{userId}:
    get:
      tags:
      - "User"
      summary: "Получить данные по стажеру с ДЗ и фидбэками"
      description: ""
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "courseId"
        required: true
        in: "path"
        description: "ID стажировки"
        type: "integer"
        format: "int64"
      - name: "userId"
        required: true
        in: "path"
        description: "ID стажера"
        type: "integer"
        format: "int64"  
      responses:
        201:
          description: "Успешная операция" 
          schema:
            $ref: "#/definitions/StudentforFeedback"   
  /promo/{courseId}/day:
    post:
      tags:
      - "Promo"
      summary: "Создание дня программы"
      description: ""
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "courseId"
        required: true
        in: "path"
        description: "ID стажировки"
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Поля таблицы Day"
        required: true
        schema:
          $ref: "#/definitions/Day"
      responses:
        201:
          description: "Успешно"
          schema:
             type: "object"
             properties:
               id:
                type: "integer"
                format: "int64"
  /promo/{courseId}/day/{dayId}:
    delete:
      tags:
      - "Promo"
      summary: "Удаление дня программы"
      description: ""
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "courseId"
        required: true
        in: "path"
        description: "ID стажировки"
        type: "integer"
        format: "int64"
      - name: "dayId"
        required: true
        in: "path"
        description: "ID дня стажировки"
        type: "integer"
        format: "int64"  
      responses:
        200:
          description: "Успешно"  
  /promo/{courseId}/program:      
    get:
      tags:
      - "Promo"
      summary: "Получение программы стажировки"
      description: ""
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "courseId"
        required: true
        in: "path"
        description: "ID стажировки"
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Успешная операция"
          schema:
            $ref: "#/definitions/Program"
  /promo/course/{courseId}/candidates:
    get:
      tags:
      - "Promo"
      summary: "Получение списка кандидатов"
      description: ""
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "courseId"
        required: true
        in: "path"
        description: "ID стажировки"
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Успешная операция"
          schema:
            $ref: "#/definitions/CandidateList"
definitions:
  ApiResponse:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
  Username:
    type: "object"
    properties:
      username:
        type: "string"    
    xml:
      name: "Username"    
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      middleName:
        type: "string"
      email:
        type: "string"
      birthday:
        type: "string"
      city:
        type: "string"
    xml:
      name: "User"
  StudentforHR:
    type: "object"
    properties:
      Firstname:
        type: "string"
      Lastname:
        type: "string"
      Middlename:
        type: "string"
      phone:
        type: "string"
      email:
        type: "string"
      birthday:
        type: "string"
        format: "date-time"
      address:
        type: "string"
    xml:
      name: "StudentforHR"    
  Credentials:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      login:
        type: "string"
      password:
        type: "string"
    xml:
      name: "Credentials"
  Course:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      startDate:
        type: "string"
        format: "date-time"
      enddate:
        type: "string"
        format: "date-time"
      archived:
        type: "boolean"
      managerId:
        type: "integer"
        format: "int32"
    xml:
      name: "Course"
  Courses:
    type: "array"
    items:
      $ref: "#/definitions/Course"
    xml:
      name: "Courses"     
  Day:
    type: "object"
    properties:
      topicId:
        type: "integer"
        format: "int64"
      number:
        type: "string"
      date:
        type: "string"
        format: "date-time"
      practicalTask:
        type: "string"
    xml:
      name: "Day"
  ProgramDay:
    type: "object"
    properties:
      topic:
        type: "string"
      number:
        type: "string"
      date:
        type: "string"
        format: "date-time"
      practicalTask:
        type: "string"
    xml:
      name: "ProgramDay"    
  Program:
    type: "array"
    items:
      $ref: "#/definitions/ProgramDay"
    xml:
      name: "Program"   
  AssignedRole:
    type: "object"
    properties:
      userId:
        type: "integer"
        format: "int64"   
      roleId:
        type: "integer"
        format: "int64"  
    xml:
      name: "AssignedRole"  
  Student:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      firstName:
        type: "string"
      lastName:
        type: "string"
      middleName:
        type: "string"
    xml:
      name: "Student"  
  StudentList:
    type: "array"
    items:
      $ref: "#/definitions/Student"
    xml:
      name: "StudentList"     
  Candidate:
    type: "object"
    properties:
      first_name:
        type: "string"
      last_name:
        type: "string"
      middle_name:
        type: "string"
      approvedbyMC:
        type: "boolean"
      approvedbySec:
        type: "boolean"  
      profileId:
        type: "integer"
        format: "int64"
      phone:
        type: "string"
    xml:
      name: "Candidate"     
  CandidateList:
    type: "array"
    items:
      $ref: "#/definitions/Candidate"
    xml:
      name: "CandidateList" 
  StudentforFeedback:
    type: "object"
    properties:
      studentId:
        type: "integer"
        format: "int64"
      Firstname:
        type: "string"
      Lastname:
        type: "string"
      Middlename:
        type: "string"
      phone:
        type: "string"
      email:
        type: "string"
      birthday:
        type: "string"
        format: "date-time"
      address:
        type: "string"
      feedback:
        type: "string"
      homeworks:
        type: "array"
        items:
          $ref: "#/definitions/Homework"
    xml:
      name: "StudentforFeedback"    
  Homework:
    type: "object"
    properties:
      lection:
        type: "string"
      task:
        type: "string"
      answer:
        type: "string"
      link:
        type: "string"
      grade:
        type: "string"
    xml:
      name: "Homework" 
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
